version: "3.8"

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: build/Dockerfile
    command: ./main
    environment:
      - GO_ENV=production
      - GIN_MODE=release
    networks:
      - appnet

  auth-service:
    build:
      context: ./auth-service
      dockerfile: build/Dockerfile
    command: ./main
    environment:
      - GO_ENV=production
    networks:
      - appnet

  user-service:
    build:
      context: ./user-service
      dockerfile: build/Dockerfile
    command: ./main
    environment:
      - GO_ENV=production
    networks:
      - appnet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - gateway
      - auth-service
      - user-service
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
