version: "3.8"
services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-service

  auth-service:
    build: ./auth-service
    ports:
      - "8082:8082"

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
