version: "3.8"

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: build/Dockerfile.dev
    volumes:
      - ./gateway:/app
    command: sh -c "go mod tidy && go run ./cmd/gateway"
    environment:
      - GO_ENV=development
      - GIN_MODE=debug
    networks:
      - appnet

  auth-service:
    build:
      context: ./auth-service
      dockerfile: build/Dockerfile.dev
    volumes:
      - ./auth-service:/app
    command: sh -c "go mod tidy && go run ./cmd/auth-service"
    environment:
      - GO_ENV=development
    networks:
      - appnet

  user-service:
    build:
      context: ./user-service
      dockerfile: build/Dockerfile.dev
    volumes:
      - ./user-service:/app
    command: sh -c "go mod tidy && go run ./cmd/user-service"
    environment:
      - GO_ENV=development
    networks:
      - appnet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - gateway
      - auth-service
      - user-service
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
